# Generated by Django 3.0.3 on 2020-07-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'journalists',
            },
        ),
        migrations.CreateModel(
            name='NewsCentre',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('news_url', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField()),
                ('content', models.TextField(null=True)),
            ],
            options={
                'db_table': 'news_centre',
                'unique_together': {('title', 'news_url')},
            },
        ),
        migrations.CreateModel(
            name='ResourceCentre',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('journalist_fname', models.CharField(max_length=20)),
                ('journalist_lname', models.CharField(max_length=20)),
                ('current_status', models.CharField(max_length=15)),
                ('assigned_date', models.DateTimeField()),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcecentres', to='automatedworkflow.Journalist')),
                ('newscentre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resourcecentres', to='automatedworkflow.NewsCentre')),
            ],
            options={
                'db_table': 'resource_centre',
            },
        ),
    ]
